export function WhyStellar() {
  return (
    <section className="py-32 px-4">
      <div className="max-w-5xl mx-auto">
        <h2
          className="font-sans font-[900] text-ink leading-[1.15] tracking-[-0.01em] text-balance"
          style={{ fontSize: 'clamp(1.75rem, 3.5vw, 2.75rem)' }}
        >
          Built for the moment Stellar made it possible.
        </h2>

        <div className="mt-8 space-y-5 max-w-[65ch]">
          <p className="font-sans font-[400] text-ink leading-[1.6] text-wrap-pretty">
            Stellar Protocol 25 and 26 introduced host functions that bring cryptographic
            primitives on-chain: Poseidon2 hashing (CAP-0075) and the Soroban execution
            environment that can verify UltraHonk proofs generated by Barretenberg. The
            result is a verifier contract that requires no trusted setup per circuit —
            each payroll circuit can be recompiled and redeployed without a ceremony.
          </p>

          <p className="font-sans font-[400] text-ink leading-[1.6] text-wrap-pretty">
            USDC is native to Stellar through Circle's Stellar Asset Contract. That means
            payroll disbursements settle in the same token organizations already use for
            treasury, with the same finality guarantees and without a bridge or wrapped
            asset. The programmable rails are real and live on Stellar testnet today.
          </p>

          <p className="font-sans font-[400] text-ink leading-[1.6] text-wrap-pretty">
            Sobre uses UltraHonk / Barretenberg for its batch-total circuit: the prover
            generates a single proof that the sum of shielded payment notes equals the
            declared total, and the Soroban verifier contract checks that proof on-chain.
            The auditor receives a view-key scoped to a single period, reconstructs the
            per-employee breakdown, and verifies it against the public predicate.
          </p>
        </div>
      </div>
    </section>
  )
}
