#!/usr/bin/env bash
# submit-real-batch.sh — Nivel A, step 5.
#
# Submits ONE real pool.transact to the deployed testnet pool whose 8
# `encrypted_outputs` carry the frozen DUAL ECIES blobs (employee + auditor
# ciphertexts) generated by gen-batch-keys-blobs.ts. The proof was produced by
# payroll-proof-gen with --ext-data-hash equal to the keccak256 over THESE exact
# blobs (computed by the pool's `print_real_batch_ext_data_hash` Rust helper), so
# the on-chain check hash_ext_data(submitted) == proof.ext_data_hash holds.
#
# ext_amount = 0: no real USDC moves (1-USDC testnet cap respected). The shielded
# amounts ([50,80,120,60,200,90,110,90], T=800) are BN254 field values, not USDC.
#
# Inputs (under ops/testnet-batch/, produced by the earlier steps):
#   proof.json          — payroll-proof-gen output (proof_arg).
#   ext_data_arg.json   — ext_data with the 8 real blob hexes.
#
# Submits WITHOUT --send=no so events actually land. Prints the tx hash + ledger.
#
# Usage: ops/scripts/submit-real-batch.sh [testnet]

set -euo pipefail

die() { echo "submit-real-batch.sh: $*" >&2; exit 1; }
need() { command -v "$1" >/dev/null 2>&1 || die "missing '$1'"; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
BATCH_DIR="$REPO_ROOT/ops/testnet-batch"
NETWORK="${1:-testnet}"
DEPLOYER="mikey"

need stellar
need jq

DEPLOYMENTS_JSON="$REPO_ROOT/ops/deployments/$NETWORK/deployments.json"
POOL_ID="$(jq -r '.noir_pool' "$DEPLOYMENTS_JSON")"

[[ -f "$BATCH_DIR/proof.json" ]] || die "missing $BATCH_DIR/proof.json (run proof gen first)"
[[ -f "$BATCH_DIR/ext_data_arg.json" ]] || die "missing $BATCH_DIR/ext_data_arg.json"

PROOF_ARG="$(jq -c '.proof_arg' "$BATCH_DIR/proof.json")"
EXT_DATA_ARG="$(jq -c '.' "$BATCH_DIR/ext_data_arg.json")"

# Guard: encrypted_outputs must be 8 NON-EMPTY blobs.
N_OUTS="$(jq -r '.encrypted_outputs | length' "$BATCH_DIR/ext_data_arg.json")"
[[ "$N_OUTS" == "8" ]] || die "expected 8 encrypted_outputs, got $N_OUTS"
EMPTY="$(jq -r '[.encrypted_outputs[] | select(. == "")] | length' "$BATCH_DIR/ext_data_arg.json")"
[[ "$EMPTY" == "0" ]] || die "found $EMPTY empty blobs; refusing to submit"

echo "==> Submitting real transact to pool $POOL_ID (network $NETWORK)" >&2
TX_HASH="$(stellar contract invoke \
  --network "$NETWORK" --source-account "$DEPLOYER" --id "$POOL_ID" \
  -- transact \
  --proof "$PROOF_ARG" \
  --ext_data "$EXT_DATA_ARG" \
  --sender "$DEPLOYER" 2>"$BATCH_DIR/submit.log" || { cat "$BATCH_DIR/submit.log" >&2; die "transact failed"; })"

echo "==> transact returned: $TX_HASH" >&2
grep -oE 'index: [0-9]+' "$BATCH_DIR/submit.log" >&2 || true

# transact returns void, so stdout is "null". The real tx hash is in the log
# ("Signing transaction: <hash>" / the stellar.expert URL). Surface that instead.
REAL_HASH="$(grep -oE 'tx/[0-9a-f]{64}' "$BATCH_DIR/submit.log" | head -1 | cut -d/ -f2)"
[[ -z "$REAL_HASH" ]] && REAL_HASH="$(grep -oiE 'Signing transaction: [0-9a-f]{64}' "$BATCH_DIR/submit.log" | grep -oE '[0-9a-f]{64}' | head -1)"
[[ -n "$REAL_HASH" ]] && echo "$REAL_HASH" || echo "$TX_HASH"
